language: ruby
rvm:
  - 2.4.0

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
 - nvm install stable
 - npm set progress=false && npm install
 - bundle install

script:
  - ./node_modules/.bin/gulp icons-download
  - npm run build
  - npm run check-links

sudo: false # route your build to the container-based infrastructure for a faster build
