language: ruby
rvm:
- 2.2

before_script:
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
  - npm install -g gulp
  
script:
  # - bundle exec jekyll build && bundle exec htmlproofer ./_site
  - gulp

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
