language: ruby
rvm:
- stable

install:
 - rvm install stable
 - nvm install stable
 - npm set progress=false && npm install
 - bundle install

script:
  - ./node_modules/.bin/gulp build-prod

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
