language: node_js
node_js:
  - "6.2.0"
  - "4.4.5"
  
before_script:
  - bundle install
  - npm install -g gulp
script: gulp

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
