language: ruby
rvm:
  - 2.6

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
 - gem install bundler
 - nvm install lts/dubnium
 - npm install
 - bundle install

script:
  - npm run download-icons
  - npm run build
  - npm run check-links
