language: ruby
rvm:
  - 2.4

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
 - nvm install lts/carbon
 - npm install
 - bundle install

script:
  - npm run download-icons
  - npm run build
  - npm run check-links

sudo: false # route your build to the container-based infrastructure for a faster build
