# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eccles Mosque
subtitle: The Eccles and Salford Islamic Society
email: info@ecclesmosque.org.uk
description: Eccles Mosque also known as The Eccles and Salford Islamic Society.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ecclesmosque.org.uk" # the base hostname & protocol for your site
enforce_ssl: ecclesmosque.org.uk

charity:
  number: 516270

author:
  twitter: EcclesMosque

twitter:
  username: EcclesMosque


# Build settings

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - vendor

markdown: kramdown

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
