# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eccles Mosque
subtitle: The Eccles and Salford Islamic Society
email: info@ecclesmosque.org.uk
description: Eccles Mosque also known as The Eccles and Salford Islamic Society.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ecclesmosque.org.uk" # the base hostname & protocol for your site

twitter:
  username: EcclesMosque


# Build settings

include: [
  '_pages'
]

exclude: [
  'README.md',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'node_modules'
]

markdown: kramdown

sass:
    sass_dir: _assets/_sass
    style: :compressed
