# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eccles Mosque
subtitle: The Eccles and Salford Islāmic Society
description: Eccles and Salford Islāmic Society also known as The Eccles Mosque.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://ecclesmosque.org.uk' # the base hostname & protocol for your site
enforce_ssl: ecclesmosque.org.uk

charitycommission:
  charityNo: 516270

contact:
  email: info@ecclesmosque.org.uk
  openday: openday@ecclesmosque.org.uk
  telephone: +44 161 789 2609
  address:
    street: 5 Liverpool Road
    town: Eccles
    city: Salford
    postcode: M30 0WB
    country: United Kingdom

# author:
# twitter: EcclesMosque
# twitter:
# username: EcclesMosque

# navigation settings
# navigation:
#   header:
#     - title: Home
#       url: /
# - title: About us
#   url: /about-us/
# - title: Projects
#   url: /projects/
#   nav: 'site.projects'
# - title: Get Involved
#   url: /get-involved/
# - title: Donate
#   url: /donate/
# - title: Contact us
#   url: /contact-us/
# footer:
#   - title: About us
#     url: /about-us/
#   - title: Contact us
#     url: /contact-us/
#   - title: Privacy
#     url: /privacy/
#   - title: Terms of Service
#     url: /terms/

social-links:
  - label: Follow us on Twitter
    url: https://twitter.com/EcclesMosque
    icon: twitter-squared
  - label: Like us on Facebook
    url: https://en-gb.facebook.com/EcclesMosque
    icon: facebook-official
  - label: Follow us on Flickr
    url: https://www.flickr.com/photos/ecclesmosque
    icon: flickr
  - label: Watch, Share and Subscribe on YouTube
    url: https://www.youtube.com/channel/UCAg5HU_BAlEU2Oo0tlhq96g?sub_confirmation=1
    icon: youtube-squared

# Build settings do not modify anything below this line
# unless you know what you are doings

# Featured Content
featured:
  updates: [] # we need to set this to an empty array so that we can filter all events and posts into this empty array

# Outputting
permalink: /:categories/:title/
# paginate: 1
# paginate_path: '/news/page/:num/'
timezone: Europe/London

include:
  - _pages

defaults:
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      type: posts
    values:
      layout: posts-entry
      thumbnail: least-i-forgot-ramadan
  - scope:
      path: events
    values:
      layout: events-entry
      thumbnail: least-i-forgot-ramadan
      seo:
        type: event
  - scope:
      path: press-releases
    values:
      layout: posts-entry
      thumbnail: press-releases
      seo:
        type: press-releases

exclude:
  - Gemfile*
  - gulpfile.*
  - eslint*
  - node_modules
  - package*
  - README.md
  - vendor

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

compress_html:
  blanklines: false
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  profile: false
  startings: []
