name: GitHub Actions Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
  
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1.1.1
      with:
        ruby-version: 2.6.x
    - name: Install Ruby dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
  
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
          node-version: '10.x'
    - name: npm install, build, and test
      run: |
        npm install
        npm run download-icons
        npm run build --if-present
        npm test
      env:
        CI: true
