name: GitHub Actions Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: npm install, build, and test
        run: |
          npm install
          npm run download-icons
          npm run build --if-present
          npm test
        env:
          CI: true
