name: GitHub Actions Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Ruby environment
        uses: actions/setup-ruby@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install Ruby Gems
        run: bundle install
        
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install npm dependencies
        run: |
          npm install
          npm run download-icons
        env:
          CI: true

      - name: Compile website
        run: |
          npm run build --if-present
          npm run test
        env:
          CI: true
